python run_attack.py \
  --dataset fashionmnist \
  --model simplecnn \
  --attack-mode random \
  --candidate-size 256 \
  --attack-size 16 \
  --topk 32 \
  --proxy-epochs 1 \
  --batch-size 32 \
  --device cpu \
  --output-dir ./outputs_fashionmnist_test